# CS224N: PyTorch Tutorial (Winter '21)

### Author: Dilara Soylu

In this notebook, we will have a basic introduction to `PyTorch` and work on a demo network solving X task [TODO write the task here]. Following resources have been used in preparation of this notebook:
* Matt's tutorial
* Official PyTorch tutorial
* GAN Class tutorial [TODO properly cite]

## Initialization

In [13]:
import torch
import numpy as np

In [14]:
import pprint
pp = pprint.PrettyPrinter()

In [15]:
x = torch.tensor([[2,2],[3,5],[4,5]],dtype = torch.float)
x

tensor([[2., 2.],
        [3., 5.],
        [4., 5.]])

In [16]:
x.int()

tensor([[2, 2],
        [3, 5],
        [4, 5]], dtype=torch.int32)

In [17]:
a = np.array([[2,2],[3,5],[4,5]])
y = torch.from_numpy(a)
y

tensor([[2, 2],
        [3, 5],
        [4, 5]])

In [18]:
x1 = torch.ones_like(x)
x1

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])